### ISSUE TITLE
vsrepo scripts with empty `published` date showing current date

### ISSUE THREAD

**Issue by OrangeChannel** [theChaosCoder/vsdb#7]
<https://github.com/vapoursynth/vsrepo/blob/349ede9be4252c2f8d0e07ac93f432d1bb892194/local/sangnom.json#L36>
<http://vsdb.top/plugins/sangnom>

<https://github.com/vapoursynth/vsrepo/blob/f754c8fb2ba7b354fcbf37e4cd0e82945c93db15/local/xvs.json#L29>
<http://vsdb.top/plugins/xvs>

![image](https://user-images.githubusercontent.com/10972040/69905980-20819800-138a-11ea-905a-d8ab9ed4423c.png)

Sort of a vsrepo issue too as the published date being empty makes no sense with git/vcs releases.

**Comment by theChaosCoder** [comment]
Thx, is fixed.
